version: '3'
services:
    web:
        image: nginx:1.21-alpine
        ports:
            - '8080:80'
        depends_on:
            - app
        volumes:
            - ./config/local/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./src/html:/var/www/html

    app:
        build:
            context: .
            dockerfile: ./docker_files/app/Dockerfile
        env_file: ./config/local/mysql.env
        environment:
            DATABASE_HOST: app-db
        depends_on:
            - app-db
        volumes:
            - ./src/html:/var/www/html

    app-db:
        build:
            context: .
            dockerfile: ./docker_files/app-db/Dockerfile
        restart: always
        env_file: ./config/local/mysql.env
        ports:
            - '3306:3306'
        volumes:
            - ./db/log:/var/log/mysql
            - ./db/data:/var/lib/mysql
            - ./db/init:/docker-entrypoint-initdb.d
